# Library

In [1]:
import os
import numpy as np 
import pandas as pd
import sklearn 

from glob import glob

# vis 
import matplotlib.pyplot as plt
import matplotlib 
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer 
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

# missing values
import miceforest as mf

In [2]:
train_dset_reg_imputation = pd.read_csv("..\\..\\data\\train_dset_reg_imputation.csv")

In [4]:
print(train_dset_reg_imputation.shape)
train_dset_reg_imputation.head()

(10270091, 17)

,loan_limit,loan_rate,is_applied,gender,credit_score,yearly_income,income_type,employment_type,houseown_type,desired_amount,purpose,personal_rehabilitation_yn,existing_loan_cnt,existing_loan_amt,event,company_year,age_group
0,20000000.0,16.5,1.0,1.0,540.0,32000000.0,0.0,3.0,2.0,10000000.0,6.0,0.0,12.0,162000000.0,8.0,9.0,5.0
1,11000000.0,16.5,0.0,1.0,580.0,72000000.0,0.0,3.0,3.0,20000000.0,6.0,0.0,7.0,106000000.0,6.0,3.0,4.0
2,3000000.0,20.0,0.0,1.0,580.0,72000000.0,0.0,3.0,3.0,20000000.0,6.0,0.0,7.0,106000000.0,6.0,3.0,4.0
3,10000000.0,13.5,0.0,1.0,740.0,39000000.0,0.0,3.0,3.0,80000000.0,7.0,0.0,2.0,58000000.0,78.0,10.0,4.0
4,22000000.0,15.9,0.0,1.0,740.0,39000000.0,0.0,3.0,3.0,80000000.0,7.0,0.0,2.0,58000000.0,78.0,10.0,4.0